# Generated by Django 5.2.9 on 2025-12-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tableAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='desk',
            options={'ordering': ['id'], 'verbose_name': 'Desk', 'verbose_name_plural': 'Desks'},
        ),
        migrations.AlterField(
            model_name='desk',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='desk',
            name='room',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
