# Generated by Django 5.2.7 on 2025-10-28 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('height', models.IntegerField(max_length=3)),
                ('activity_level', models.IntegerField(max_length=3)),
                ('role', models.CharField(max_length=20)),
                ('table_id', models.IntegerField(db_default=None)),
            ],
        ),
    ]
