# Generated by Django 5.2.7 on 2025-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_users_table_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='table_id',
            field=models.IntegerField(db_default=None, null=True),
        ),
    ]
