# Generated by Django 5.2.7 on 2025-10-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_users_table_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activity_level',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='users',
            name='height',
            field=models.IntegerField(),
        ),
    ]
