# Generated by Django 5.1.1 on 2025-11-23 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_room_desklayout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeskLayout',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
