# Generated by Django 5.1.1 on 2025-10-29 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_users_activity_level_alter_users_height'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='activity_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='role',
            field=models.CharField(default='user', max_length=20),
        ),
    ]
