# Generated by Django 5.2.7 on 2025-10-29 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_positionchanges_statistics_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="Tables",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("height", models.IntegerField()),
                ("api_key", models.CharField()),
            ],
        ),
        migrations.RenameModel(
            old_name="Table",
            new_name="UserTablePairs",
        ),
    ]
