# Generated by Django 5.2.7 on 2025-12-14 19:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_deskbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertablepairs',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
