# Generated by Django 5.1.1 on 2025-11-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_add_gender_choices'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
