# Generated by Django 5.1.1 on 2025-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_tables_rename_table_usertablepairs'),
        ('main', '0007_add_approved_attribute'),
    ]

    operations = [
    ]
