# Generated by Django 5.2.7 on 2025-12-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_usertablepairs_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertablepairs',
            name='height_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
