# Generated by Django 5.2.7 on 2025-12-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_usertablepairs_height_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='deskbooking',
            name='height_history',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
