# Generated by Django 5.1.1 on 2025-11-07 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_merge_conflicts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tables',
            name='api_key',
            field=models.CharField(max_length=255),
        ),
    ]
