# Generated by Django 5.2.7 on 2025-11-15 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_passwordresetrequest'),
        ('main', '0010_user_table_pairs'),
    ]

    operations = [
    ]
